/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.jack.encoding.tests.iso8859dash1;

import junit.framework.Assert;

import org.junit.Test;

public class EncodingIso8859dash1Tests {
  private static final String STRINGS[] = {
    "Voix ambiguë d'un coeur qui au zéphyr préfère les jattes de kiwi",
    "Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich",
    "Queda gazpacho, fibra, látex, jamón, kiwi y viñas",
  };

  @Test
  public void testEncoding() {
    // Can be generated by the main() helper
    testString(STRINGS[0],
        new char[] {86, 111, 105, 120, 32, 97, 109, 98, 105, 103, 117, 235, 32, 100, 39, 117, 110,
                    32, 99, 111, 101, 117, 114, 32, 113, 117, 105, 32, 97, 117, 32, 122, 233, 112,
                    104, 121, 114, 32, 112, 114, 233, 102, 232, 114, 101, 32, 108, 101, 115, 32,
                    106, 97, 116, 116, 101, 115, 32, 100, 101, 32, 107, 105, 119, 105});
    testString(STRINGS[1],
        new char[] {86, 105, 99, 116, 111, 114, 32, 106, 97, 103, 116, 32, 122, 119, 246, 108, 102,
                    32, 66, 111, 120, 107, 228, 109, 112, 102, 101, 114, 32, 113, 117, 101, 114, 32,
                    252, 98, 101, 114, 32, 100, 101, 110, 32, 103, 114, 111, 223, 101, 110, 32, 83,
                    121, 108, 116, 101, 114, 32, 68, 101, 105, 99, 104});
    testString(STRINGS[2],
        new char[] {81, 117, 101, 100, 97, 32, 103, 97, 122, 112, 97, 99, 104, 111, 44, 32, 102,
                    105, 98, 114, 97, 44, 32, 108, 225, 116, 101, 120, 44, 32, 106, 97, 109, 243,
                    110, 44, 32, 107, 105, 119, 105, 32, 121, 32, 118, 105, 241, 97, 115});
  }

  public static void main(String[] argv) {
    dumpTest(STRINGS);
  }

  private void testString(String string, char[] ref) {
    Assert.assertEquals(new String(ref), string);
  }

  private static void dumpTest(String[] strings) {
    int index = 0;
    for (String string : strings) {
      System.out.print("    testString(STRINGS[" + index++ + "], new char[]{");
      boolean first = true;
      for (char c : string.toCharArray()) {
        if (!first) {
          System.out.print(",");
        } else {
          first = false;
        }
        System.out.print((int) c);
      }
      System.out.println("});");
    }
  }
}
