#!/bin/bash
#
# Copyright (C) 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Version: %%VERSION%%
#
set -o nounset
umask 077

#
# Settings
#
JACK_HOME="${JACK_HOME:=$HOME/.jack-home}"
CLIENT_SETTING="${CLIENT_SETTING:=$HOME/.jack-client}"
TMPDIR=${TMPDIR:=/tmp}
JACK_SERVER_VM_ARGUMENTS="${JACK_SERVER_VM_ARGUMENTS:=-Dfile.encoding=UTF-8 -XX:+TieredCompilation}"

LAUNCHER_JAR="$JACK_HOME/launcher.jar"
LAUNCHER_NAME=com.android.jack.launcher.ServerLauncher


#
# Load client settings
#
if [ -f "$CLIENT_SETTING" ]; then
  source "$CLIENT_SETTING"
fi

#
# Create or update client settings if needed
#
if [[ ! -f "$CLIENT_SETTING" || $SETTING_VERSION -lt 4 ]]; then
  echo "Writing client settings in" $CLIENT_SETTING
  cat >"$CLIENT_SETTING.$$" <<-EOT
	# Server settings
	SERVER_HOST=${SERVER_HOST:=127.0.0.1}
	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8074}
	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8075}

	# Internal, do not touch
	SETTING_VERSION=4
EOT
  ln -f "$CLIENT_SETTING.$$" "$CLIENT_SETTING"
  rm "$CLIENT_SETTING.$$"
  source "$CLIENT_SETTING"
fi

usage () {
  echo "Usage : $0 [ install-server <launcher.jar> <server.jar> | list <program> | install <program> <program.jar> | start-server | stop-server | kill-server | list-server | server-stat ]"
}

abort () { exit 255; }

#
# $1: curl command status
# $2: HTTP status
#
handleHttpErrors() {
  if [ $1 -eq 0 ]; then
    # No problem, let's go
    return 0;
  elif [ $1 -eq 7 ]; then
    echo "ERROR: No Jack server running" >&2
    abort
  elif  [ $1 -eq 22 ]; then
    # Http code not OK, let's decode and abort
    if [ $2 -eq 401 ]; then
      # 401: Unauthorized
      echo "ERROR: Security problem, see Jack server log" >&2
      abort
    elif [ $2 -eq 400 ]; then
      # 400: Bad request
      echo "ERROR: Bad request, see Jack server log" >&2
      abort
    else
      # Other
      echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
      abort
    fi
  else
    # In case of partial, timeout, empty respond, network error, let's retry
    if [ $RETRY_SESSION -eq 0 ]; then
      echo "ERROR: Communication error with Jack server $CURL_CODE" >&2
      abort
    else
      let RETRY_SESSION=RETRY_SESSION-1
      return 1;
    fi
  fi
}

#
# $1: program name
# $2: jar of the program
#
installProgram () {
  RETRY_SESSION=3
  DONE=1
  while [ "$DONE" -ne 0 ]; do
    exec 3>&1
    HTTP_CODE=$(curl -f \
         --output >(cat >&3) \
         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
         -X PUT \
         -F "jar=@$2;type=application/octet-stream" \
         -F "force=$FORCE_INSTALLATION;type=text/plain" \
         --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
         http://${SERVER_HOST}:$SERVER_PORT_ADMIN/$1 \
         )
    handleHttpErrors $? $HTTP_CODE
    DONE=$?
    exec 3>&-
  done

  if [ "$1" == server ]; then
    waitServerStarted
  fi
}

isServerRunning () {
  RETRY_SESSION=3
  DONE=1
  while [ "$DONE" -ne 0 ]; do
    HTTP_CODE=$(curl -f \
         --output >(cat >/dev/null) \
         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
         -X GET \
         -H "Accept: text/plain" \
         --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
         http://${SERVER_HOST}:$SERVER_PORT_ADMIN/server \
         )
    CURL_CODE=$?
    if [ $CURL_CODE -eq 0 ]; then
      # No problem, let's go
      return 0;
    elif [ $CURL_CODE -eq 7 ]; then
      return 1
    elif  [ $CURL_CODE -eq 22 ]; then
      # Http code not OK, let's decode and abort
      if [ $HTTP_CODE -eq 401 ]; then
        # 401: Unauthorized
        echo "ERROR: Security problem, see Jack server log" >&2
        abort
      elif [ $HTTP_CODE -eq 400 ]; then
        # 400: Bad request
        echo "ERROR: Bad request, see Jack server log" >&2
        abort
      else
        # Other
        echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
        abort
      fi
    else
      # In case of partial, timeout, empty respond, network error, let's retry
      if [ $RETRY_SESSION -eq 0 ]; then
        echo "ERROR: Communication error with Jack server $CURL_CODE" >&2
        abort
      else
        let RETRY_SESSION=RETRY_SESSION-1
      fi
    fi
  done
}

startServer () {
  isServerRunning
  RUNNING=$?
  if [ "$RUNNING" = 0 ]; then
    echo "Server is already running"
  else
    JACK_SERVER_COMMAND="java -Djava.io.tmpdir=$TMPDIR $JACK_SERVER_VM_ARGUMENTS -cp $LAUNCHER_JAR $LAUNCHER_NAME"
    echo "Launching Jack server" $JACK_SERVER_COMMAND
    nohup $JACK_SERVER_COMMAND >/dev/null 2>/dev/null &
  fi
}

waitServerStarted () {
  RETRY_SESSION=6
  DONE=1
  while [ "$DONE" -ne 0 ]; do
    HTTP_CODE=$(curl -f \
         --output >(cat >/dev/null) \
         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
         -X GET \
         -H "Accept: text/plain" \
         --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
         http://${SERVER_HOST}:$SERVER_PORT_ADMIN/server \
         )
    CURL_CODE=$?
    if [ $CURL_CODE -eq 0 ]; then
      # No problem, let's go
      DONE=0;
    elif [ $CURL_CODE -eq 7 ]; then
      if [ $RETRY_SESSION -eq 0 ]; then
        echo "ERROR: No Jack server running" &>2
        abort
      else
        let RETRY_SESSION=RETRY_SESSION-1
        sleep 1;
      fi
    elif  [ $CURL_CODE -eq 22 ]; then
      # Http code not OK, let's decode and abort
      if [ $HTTP_CODE -eq 401 ]; then
        # 401: Unauthorized
        echo "ERROR: Security problem, see Jack server log" >&2
        abort
      elif [ $HTTP_CODE -eq 400 ]; then
        # 400: Bad request
        echo "ERROR: Bad request, see Jack server log" >&2
        abort
      else
        # Other
        echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
        abort
      fi
    else
      # In case of partial, timeout, empty respond, network error, let's retry
      if [ $RETRY_SESSION -eq 0 ]; then
        echo "ERROR: Communication error with Jack server $CURL_CODE" >&2
        abort
      else
        let RETRY_SESSION=RETRY_SESSION-1
      fi
    fi
  done
}
#
# $1: program name
#
listProgramVersion () {
  RETRY_SESSION=3
  DONE=1
  while [ "$DONE" -ne 0 ]; do
    exec 3>&1
    HTTP_CODE=$(curl -f \
         --output >(cat >&3) \
         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
         -X GET \
         -H "Accept: text/plain" \
         --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
         http://${SERVER_HOST}:$SERVER_PORT_ADMIN/$1 \
         )
    handleHttpErrors $? $HTTP_CODE
    DONE=$?
    exec 3>&-
  done
}

#
# Decoding argument
#
if [ $# -eq 0 ]
then
  usage
  abort
fi

set +o errexit

FORCE_INSTALLATION=false
case $1 in
  force-install-server)
    FORCE_INSTALLATION=true
    COMMAND=install-server;;
  force-install)
    FORCE_INSTALLATION=true
    COMMAND=install;;
  *)
    COMMAND=$1;;
esac

case $COMMAND in
  install-server)
    if [ $# -lt 3 ]; then
      usage
      abort
    fi
    if [ $# -gt 4 ]; then
      usage
      abort
    fi
    if [ ! -r "$2" ]; then
      echo "ERROR: \"$2\" is not a readable file" 1>&2
      usage
      abort
    fi
     if [ ! -r "$3" ]; then
      echo "ERROR: \"$3\" is not a readable file" 1>&2
      usage
      abort
    fi

    if [ ! -d "$JACK_HOME" ]; then
      echo Installing jack server in \"$JACK_HOME\"
      mkdir -p "$JACK_HOME"
      cp $2 "$LAUNCHER_JAR"
      cp $3 "$JACK_HOME/server-1.jar"
      mkdir "$JACK_HOME"/logs
      startServer
      waitServerStarted
    else
      echo \"$JACK_HOME\" already exists. Skipping installation of launcher
      startServer
      waitServerStarted
      installProgram server $3
    fi
    exit 0 ;;


  list)
    if [ $# -ne 2 ]
    then
      usage
      abort
    fi

    listProgramVersion $2 ;;


  install)
    if [ $# -ne 3 ]; then
      usage
      abort
    fi

    if [ ! -r "$3" ]; then
      echo "ERROR: \"$3\" is not a readable file" 1>&2
      usage
      abort
    fi
    installProgram $2 $3 ;;


  stop-server)
    echo "Stopping background server"

    RETRY_SESSION=3
    DONE=1
    while [ "$DONE" -ne 0 ]; do
      exec 3>&1
      HTTP_CODE=$(curl -f \
           --output >(cat >&3) \
           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
           -X POST \
           --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
           http://${SERVER_HOST}:$SERVER_PORT_ADMIN/server/stop \
           )
      handleHttpErrors $? $HTTP_CODE
      DONE=$?
      exec 3>&-
    done ;;


  server-stat)
    echo "Getting statistic from background server"

    RETRY_SESSION=3
    DONE=1
    while [ "$DONE" -ne 0 ]; do
      exec 3>&1
      HTTP_CODE=$(curl -f \
           --output >(cat >&3) \
           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
           -X GET \
           -H "Accept: text/plain" \
           --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
           http://${SERVER_HOST}:$SERVER_PORT_ADMIN/stat \
           )
      handleHttpErrors $? $HTTP_CODE
      DONE=$?
      exec 3>&-
    done ;;


  server-log)
    echo "Command server-log is not supported any more" 1>&2
    abort ;;


  kill-server)
    echo "Killing background server"
    kill $(ps aux | grep $LAUNCHER_NAME | grep -v grep | awk '{print $2}') 2>/dev/null
    if [ $? -ne 0 ]; then
      echo "ERROR: No Jack server to kill" >&2
      exit 2
    else
      exit 0
    fi ;;


  list-server)
    ps aux | grep $LAUNCHER_NAME | grep -v grep
    exit $? ;;


  start-server)
    startServer
    waitServerStarted
    exit 0 ;;


  *)
    usage
    abort ;;
esac


# Exit

exit 0
