/*
 * Copyright (C) 2014 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.jack.errorhandling;

import com.google.common.io.Files;

import com.android.jack.JackUserException;
import com.android.jack.Main;
import com.android.jack.Options;
import com.android.jack.TestTools;
import com.android.jack.errorhandling.annotationprocessor.ResourceAnnotationProcessor;
import com.android.jack.errorhandling.annotationprocessor.ResourceAnnotationTest;
import com.android.jack.errorhandling.annotationprocessor.SourceAnnotationProcessor;
import com.android.jack.errorhandling.annotationprocessor.SourceAnnotationTest;
import com.android.jack.errorhandling.annotationprocessor.SourceErrorAnnotationTest;
import com.android.jack.frontend.FrontendCompilationException;
import com.android.jack.util.FileUtils;

import junit.framework.Assert;

import org.jf.dexlib.ClassDefItem;
import org.jf.dexlib.DexFile;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.File;
import java.io.FileReader;
import java.io.LineNumberReader;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Nonnull;

/**
 * JUnit test checking Jack behavior when using annotation processor.
 */
public class AnnotationProcessorErrorTest {

  @BeforeClass
  public static void setUpClass() {
    Main.class.getClassLoader().setDefaultAssertionStatus(true);
  }

  /**
   * Checks that compilation fails correctly when annotation processor is called without specifying
   * output folder.
   */
  @Test
  public void testAnnotationProcessorError001() throws Exception {
    TestingEnvironment te = new TestingEnvironment();

    te.addFile(te.getSourceFolder(),"jack.incremental", "A.java",
        "package jack.incremental; \n"+
        "public class A {} \n");

    Options options = new Options();
    List<String> ecjArgs = new ArrayList<String>();
    ecjArgs.add("-processor");
    ecjArgs.add(ResourceAnnotationProcessor.class.getName());
    ecjArgs.add(te.getSourceFolder().getAbsolutePath());
    options.setEcjArguments(ecjArgs);
    options.setClasspath(TestTools.getDefaultBootclasspathString());

    try {
      te.compile(options);
      Assert.fail();
    } catch (JackUserException e) {
      // Failure is ok since output for annotation processor is not specify.
      Assert.assertTrue(e.getMessage().contains("Unknown location"));
    }
  }

  /**
   * Checks that compilation succeed when running annotation processor to generate resource file.
   */
  @Test
  public void testAnnotationProcessorError002() throws Exception {
    runAnnotProcBuildingResource(new TestingEnvironment());
  }

  /**
   * Checks that last compilation failed since the resource created by annotation processor already
   * exist.
   */
  @Test
  public void testAnnotationProcessorError003() throws Exception {
    TestingEnvironment te = new TestingEnvironment();

    runAnnotProcBuildingResource(te);

    Options options = new Options();
    List<String> ecjArgs = new ArrayList<String>();
    ecjArgs.add("-d");
    ecjArgs.add(te.getTestingFolder().getAbsolutePath());
    ecjArgs.add("-processor");
    ecjArgs.add(ResourceAnnotationProcessor.class.getName());
    ecjArgs.add(te.getSourceFolder().getAbsolutePath());
    options.setEcjArguments(ecjArgs);
    options.setClasspath(TestTools.getDefaultBootclasspathString() + File.pathSeparator
        + te.getJackFolder());
    options.setOutputDir(TestTools.createTempDir("annot", "dex"));

    try {
      te.startErrRedirection();
      te.compile(options);
      Assert.fail();
    } catch (FrontendCompilationException e) {
      // Failure is ok since created file already exists
    } finally {
      Assert.assertTrue(te.endErrRedirection().contains("Resource already created"));
    }
  }

  /**
   * Checks that compilation failed since the source file generated by the annotation processor
   * does not compile.
   */
  @Test
  public void testAnnotationProcessorError004() throws Exception {
    TestingEnvironment te = new TestingEnvironment();

    buildAnnotationRequiredByAnnotationProc(te, new Class<?>[] {SourceAnnotationTest.class,
        SourceErrorAnnotationTest.class});

    te.addFile(te.getSourceFolder(), "jack.incremental", "A.java", "package jack.incremental;\n"
        + "import " + SourceErrorAnnotationTest.class.getName() + ";\n"
        + "@" + SourceErrorAnnotationTest.class.getSimpleName() + "\n"
        + "public class A {}\n");

    Options options = new Options();
    List<String> ecjArgs = new ArrayList<String>();
    ecjArgs.add("-d");
    ecjArgs.add(te.getTestingFolder().getAbsolutePath());
    ecjArgs.add("-processor");
    ecjArgs.add(SourceAnnotationProcessor.class.getName());
    ecjArgs.add(te.getSourceFolder().getAbsolutePath());
    options.setEcjArguments(ecjArgs);
    options.setClasspath(TestTools.getDefaultBootclasspathString() + File.pathSeparator
        + te.getJackFolder());

    try {
      te.startErrRedirection();
      te.compile(options);
      Assert.fail();
    } catch (FrontendCompilationException ex) {
      // Failure is ok since source generated by annotation processor does not compile.
    } finally {
      Assert.assertTrue(te.endErrRedirection().contains("Syntax error on tokens, delete these tokens"));
    }
  }

  /**
   * Checks that compilation succeed to compile source file generated by the annotation processor.
   */
  @Test
  public void testAnnotationProcessorError005() throws Exception {
    TestingEnvironment te = new TestingEnvironment();

    buildAnnotationRequiredByAnnotationProc(te, new Class<?>[] {SourceAnnotationTest.class,
        SourceErrorAnnotationTest.class});

    te.addFile(te.getSourceFolder(), "jack.incremental", "A.java", "package jack.incremental;\n"
        + "import " + SourceAnnotationTest.class.getName() + ";\n"
        + "@" + SourceAnnotationTest.class.getSimpleName() + "\n"
        + "public class A {}\n");

    Options options = new Options();
    List<String> ecjArgs = new ArrayList<String>();
    ecjArgs.add("-d");
    ecjArgs.add(te.getTestingFolder().getAbsolutePath());
    ecjArgs.add("-processor");
    ecjArgs.add(SourceAnnotationProcessor.class.getName());
    ecjArgs.add(te.getSourceFolder().getAbsolutePath());
    options.setEcjArguments(ecjArgs);
    options.setClasspath(TestTools.getDefaultBootclasspathString() + File.pathSeparator
        + te.getJackFolder());

    File dexOutput = new File(te.getTestingFolder(), "classes.dex");
    options.setOutputDir(te.getTestingFolder());

    te.compile(options);

    DexFile dexFile = new DexFile(dexOutput);
    List<String> sourceFileInDex = new ArrayList<String>();
    for (ClassDefItem classDef : dexFile.ClassDefsSection.getItems()) {
      sourceFileInDex.add(classDef.getSourceFile().getStringValue());
    }

    Assert.assertTrue(sourceFileInDex.contains("ADuplicated.java"));
    Assert.assertTrue(sourceFileInDex.contains("A.java"));
  }

  private void runAnnotProcBuildingResource(@Nonnull TestingEnvironment te) throws Exception {

    buildAnnotationRequiredByAnnotationProc(te, new Class<?>[] {ResourceAnnotationTest.class});

    te.addFile(te.getSourceFolder(), "jack.incremental", "A.java", "package jack.incremental;\n"
        + "import " + ResourceAnnotationTest.class.getName() + ";\n"
        + "@" + ResourceAnnotationTest.class.getSimpleName() + "\n"
        + "public class A {}\n");

    Options options = new Options();
    List<String> ecjArgs = new ArrayList<String>();
    ecjArgs.add("-d");
    ecjArgs.add(te.getTestingFolder().getAbsolutePath());
    ecjArgs.add("-processor");
    ecjArgs.add(ResourceAnnotationProcessor.class.getName());
    ecjArgs.add(te.getSourceFolder().getAbsolutePath());
    options.setEcjArguments(ecjArgs);
    options.setClasspath(TestTools.getDefaultBootclasspathString() + File.pathSeparator
        + te.getJackFolder());
    options.setOutputDir(TestTools.createTempDir("annot", "dex"));

    te.compile(options);

    File discoverFile = new File(te.getTestingFolder(), ResourceAnnotationProcessor.FILENAME);
    Assert.assertTrue(discoverFile.exists());
    LineNumberReader lnr = new LineNumberReader(new FileReader(discoverFile));
    Assert.assertEquals(ResourceAnnotationTest.class.getName(), lnr.readLine());
    Assert.assertEquals("jack.incremental.A", lnr.readLine());
    Assert.assertNull(lnr.readLine());
    lnr.close();
  }

  private void buildAnnotationRequiredByAnnotationProc(@Nonnull TestingEnvironment te,
      @Nonnull Class<?>[] annotationClasses) throws Exception {
    File targetAnnotationFileFolder =
        new File(te.getSourceFolder(), "com/android/jack/errorhandling/annotationprocessor/");
    if (!targetAnnotationFileFolder.mkdirs()) {
      Assert.fail("Fail to create folder " + targetAnnotationFileFolder.getAbsolutePath());
    }

    for (Class<?> annotationClass : annotationClasses) {
    Files.copy(new File(TestTools.getAndroidTop()
        + "/toolchain/jack/jack/tests/com/android/jack/errorhandling/annotationprocessor/"
        + annotationClass.getSimpleName() + ".java"), new File(
        targetAnnotationFileFolder, annotationClass.getSimpleName() + ".java"));
    }

    // Compile annotation to a jack file
    Options options = new Options();
    List<String> ecjArgs = new ArrayList<String>();
    ecjArgs.add(te.getSourceFolder().getAbsolutePath());
    options.setEcjArguments(ecjArgs);
    options.setClasspath(TestTools.getDefaultBootclasspathString());
    options.setJayceOutputDir(te.getJackFolder());

    te.compile(options);

    FileUtils.deleteDir(te.getSourceFolder());
  }
}
